name: Lint Python code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.5.1
